CreateRedmineIndex = "redmine_index"
CreatePortalIndex = "portal_index"
CreateNotionIndex = "notion_index"
IngestRedmineData = "ingest_redmine"
IngestPortalData = "ingest_portal"
IngestNotionData = "ingest_notion"